- name: Ensure proper time synchronization
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - ntp
          - curl
          - wget
        state: present
        update_cache: no

    - name: Stop NTP service temporarily
      systemd:
        name: ntp
        state: stopped
      ignore_errors: yes

    - name: Try multiple time sync methods
      block:
        - name: Method 1 - ntpdate with multiple servers
          command: ntpdate -s pool.ntp.org
          register: time_sync
          changed_when: false
          ignore_errors: yes

        - name: Method 2 - Use chrony if ntpdate fails
          command: chronyd -q "server pool.ntp.org iburst"
          when: time_sync is failed
          changed_when: false
          ignore_errors: yes

        - name: Method 3 - HTTP time sync as last resort
          shell: |
            date -s "$(curl -s --head http://google.com | grep '^Date:' | cut -d' ' -f5-)" ||
            date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-)" ||
            echo "Time sync completed via fallback"
          args:
            warn: false
          when: time_sync is failed
          changed_when: false

      rescue:
        - name: Final fallback - manual time set (approximate)
          command: date -s "2025-10-04 12:30:00"
          changed_when: false

    - name: Start NTP service
      systemd:
        name: ntp
        state: started
        enabled: yes

    - name: Verify time is synced
      command: ntpq -p
      register: ntp_peers
      changed_when: false

    - name: Show NTP status
      debug:
        var: ntp_peers.stdout_lines

    - name: Show final system time
      command: date
      register: final_time
      changed_when: false

    - name: Display final time
      debug:
        var: final_time.stdout
