- name: Fix time synchronization issue
  hosts: all
  become: yes
  tasks:
    - name: Install ntpdate
      apt:
        name: ntpdate
        state: present
        update_cache: no  # Skip apt update since that's failing

    - name: Sync time with NTP server
      command: ntpdate -s ntp.ubuntu.com
      
    - name: Install and configure ntp
      apt:
        name: ntp
        state: present
        update_cache: no
        
    - name: Restart ntp service
      systemd:
        name: ntp
        state: restarted
